#!/usr/bin/env node

const loadConfig = require( 'read-config' )
    , config     = loadConfig( './config.yml' );

const app        = require('./lib/routes');

const address = config.http.address || '0.0.0.0';
const port = config.http.port || 3000;

// Start listening for HTTP requests
const server = app.listen(port, address, function() {
  console.log('API listening at %s:%s', address, port);
});
server.on('error', function(err) {
  if (err.code === 'EADDRINUSE') {
    console.log('port %s is already in use!', port);
  } else {
    console.log('unkown error while launching server!')
  }
  process.exit(1);
});