---
# all settings to connect to the database (mysql)
database:
  host: 192.168.56.101
  port: 3306
  user: omni_api
  password: secret
  name: omni_loader

# all settings for the local http interface
http:
  address: 0.0.0.0
  port: 3000
  hostname: localhost:4200
  allowMethods: GET, POST

# all settings for Celery
celery:
  availableTasks: [ echo, download ]
  broker: amqp://
  backend: amqp://
  workerName: omni

path:
  plexRoot: /tmp/plex